# Generated by Django 6.0.4 on 2026-05-19 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="points",
        ),
    ]
